/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import {
  CacheFirst,
  NetworkFirst,
  StaleWhileRevalidate,
} from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// ── Navigation requests → Network First with offline fallback ──
const navigationHandler = new NetworkFirst({
  cacheName: "navigation",
  networkTimeoutSeconds: 5,
  plugins: [
    new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 24 * 60 * 60 }),
  ],
});

const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [/^\/~oauth/],
});
registerRoute(navigationRoute);

// ── Static assets (images, fonts) → Cache First ──
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp|avif|ico|woff2?)$/i,
  new CacheFirst({
    cacheName: "static-assets",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Google Fonts stylesheets → Stale While Revalidate ──
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: "google-fonts-stylesheets",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 365 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Google Fonts files → Cache First ──
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: "google-fonts-webfonts",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Supabase Storage → Stale While Revalidate ──
registerRoute(
  /^https:\/\/.*\.supabase\.co\/storage\/.*/i,
  new StaleWhileRevalidate({
    cacheName: "supabase-storage",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Supabase API → Network First ──
registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/.*/i,
  new NetworkFirst({
    cacheName: "supabase-api",
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 300 }),
    ],
  })
);

// ── Edge Functions → Network First ──
registerRoute(
  /^https:\/\/.*\.supabase\.co\/functions\/.*/i,
  new NetworkFirst({
    cacheName: "supabase-functions",
    networkTimeoutSeconds: 15,
    plugins: [
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 60 }),
    ],
  })
);

// Pre-cache the offline page on install
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open("offline-fallback").then((cache) => cache.add("/offline.html"))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// ── Offline fallback: only show offline.html when truly offline ──
// Workbox NavigationRoute (NetworkFirst) handles navigation normally.
// This handler is a safety net that ONLY fires when the network fetch
// inside NavigationRoute throws (i.e. no connectivity at all).
// We override the handlerDidError lifecycle to serve offline.html.
navigationHandler.plugins.push({
  handlerDidError: async () => {
    const offlineCache = await caches.open("offline-fallback");
    return (await offlineCache.match("/offline.html")) ||
      new Response("أنت غير متصل بالإنترنت", {
        status: 503,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
  },
});
