/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import {
  CacheFirst,
  NetworkFirst,
  StaleWhileRevalidate,
} from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string | null }>;
};

// Precache all assets generated by the build
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// ── Navigation requests → Network First with offline fallback ──
const navigationHandler = new NetworkFirst({
  cacheName: "navigation",
  networkTimeoutSeconds: 5,
  plugins: [
    new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 24 * 60 * 60 }),
  ],
});

const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [/^\/~oauth/],
});
registerRoute(navigationRoute);

// ── Static assets (images, fonts) → Cache First ──
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp|avif|ico|woff2?)$/i,
  new CacheFirst({
    cacheName: "static-assets",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Google Fonts stylesheets → Stale While Revalidate ──
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: "google-fonts-stylesheets",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 365 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Google Fonts files → Cache First ──
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: "google-fonts-webfonts",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Supabase Storage → Stale While Revalidate ──
registerRoute(
  /^https:\/\/.*\.supabase\.co\/storage\/.*/i,
  new StaleWhileRevalidate({
    cacheName: "supabase-storage",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Supabase API → Network ONLY (no caching to avoid stale AI analysis data) ──
registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/.*/i,
  new NetworkFirst({
    cacheName: "supabase-api",
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 30 }),
    ],
  })
);

// ── Edge Functions → Network First ──
registerRoute(
  /^https:\/\/.*\.supabase\.co\/functions\/.*/i,
  new NetworkFirst({
    cacheName: "supabase-functions",
    networkTimeoutSeconds: 15,
    plugins: [
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 60 }),
    ],
  })
);

// Pre-cache offline fallback on install
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open("offline-fallback").then((cache) => cache.add("/offline.html"))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// ── Push Notifications ──
self.addEventListener("push", (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const options: NotificationOptions = {
      body: data.body || "",
      icon: data.icon || "/pwa-icon-192.png",
      badge: data.badge || "/pwa-icon-192.png",
      dir: "rtl" as NotificationDirection,
      lang: "ar",
      tag: data.tag || "default",
      data: { url: data.url || "/", ...data.data },
      requireInteraction: true,
    } as any;



    event.waitUntil(
      self.registration.showNotification(data.title || "سوق تقبيل", options)
    );
  } catch (err) {
    console.error("Push event error:", err);
  }
});

// ── Notification click handler ──
self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const url = event.notification.data?.url || "/";

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        // Focus existing window if available
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && "focus" in client) {
            client.navigate(url);
            return client.focus();
          }
        }
        // Open new window
        return self.clients.openWindow(url);
      })
  );
});

// ── SPA fallback: return cached /index.html first, then offline.html ──
navigationHandler.plugins.push({
  handlerDidError: async () => {
    // Try the precached SPA shell first (index.html)
    const precached = await caches.match(
      new Request("/index.html"),
      { ignoreSearch: true }
    );
    if (precached) return precached;

    // Last resort: offline page
    const offlineCache = await caches.open("offline-fallback");
    return (await offlineCache.match("/offline.html")) ||
      new Response("أنت غير متصل بالإنترنت", {
        status: 503,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
  },
});
